// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnxdhm7oMTY64xWJ88gNRxq8ntzqliZY',
    appId: '1:526643428789:web:33014ed7b7d4cb96d72dfc',
    messagingSenderId: '526643428789',
    projectId: 'eilajaa-29dcf',
    authDomain: 'eilajaa-29dcf.firebaseapp.com',
    storageBucket: 'eilajaa-29dcf.firebasestorage.app',
    measurementId: 'G-QDVL5HY9GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxAtalSE72UKNw-zkdy0QNqMv-k3r_7E',
    appId: '1:526643428789:android:a719d4b694ebbfefd72dfc',
    messagingSenderId: '526643428789',
    projectId: 'eilajaa-29dcf',
    storageBucket: 'eilajaa-29dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtiEnuuDGTswWTsDLmSER8jyA1ISGlL3I',
    appId: '1:526643428789:ios:2da92e3c08b2adc3d72dfc',
    messagingSenderId: '526643428789',
    projectId: 'eilajaa-29dcf',
    storageBucket: 'eilajaa-29dcf.firebasestorage.app',
    androidClientId: '526643428789-f8ga8g35ibl6boqvqcmi869qell354d7.apps.googleusercontent.com',
    iosClientId: '526643428789-pqo0iojdt4o7p75eju6vgrmo9ubgojfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtiEnuuDGTswWTsDLmSER8jyA1ISGlL3I',
    appId: '1:526643428789:ios:2da92e3c08b2adc3d72dfc',
    messagingSenderId: '526643428789',
    projectId: 'eilajaa-29dcf',
    storageBucket: 'eilajaa-29dcf.firebasestorage.app',
    androidClientId: '526643428789-f8ga8g35ibl6boqvqcmi869qell354d7.apps.googleusercontent.com',
    iosClientId: '526643428789-pqo0iojdt4o7p75eju6vgrmo9ubgojfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQnxdhm7oMTY64xWJ88gNRxq8ntzqliZY',
    appId: '1:526643428789:web:3b0afbfe5d942f13d72dfc',
    messagingSenderId: '526643428789',
    projectId: 'eilajaa-29dcf',
    authDomain: 'eilajaa-29dcf.firebaseapp.com',
    storageBucket: 'eilajaa-29dcf.firebasestorage.app',
    measurementId: 'G-1LTYD8W997',
  );
}
